# Default params
server:
  host: "0.0.0.0"
  port: "8081"

# Default params
database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "subscription_db"
  sslmode: "disable"

logger:
  level: "info"
  format: "json"

env: "development"
