basePath: /api/v1
definitions:
  echo.Map:
    additionalProperties: true
    type: object
  github_com_untibullet_subscription-service-em_internal_models.Subscription:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  internal_service.costResp:
    properties:
      total:
        type: integer
    type: object
  internal_service.createReq:
    properties:
      end_date:
        description: MM-YYYY
        type: string
      price:
        type: integer
      service_name:
        maxLength: 255
        minLength: 1
        type: string
      start_date:
        description: MM-YYYY
        type: string
      user_id:
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  internal_service.listResp:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_untibullet_subscription-service-em_internal_models.Subscription'
        type: array
      total:
        type: integer
    type: object
  internal_service.updateReq:
    properties:
      end_date:
        description: MM-YYYY
        type: string
      price:
        type: integer
      service_name:
        maxLength: 255
        minLength: 1
        type: string
      start_date:
        description: MM-YYYY
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: API для управления подписками
  title: Subscription Service API
  version: "1.0"
paths:
  /api/v1/subscriptions:
    get:
      consumes:
      - application/json
      description: Возвращает список подписок с фильтрацией и пагинацией
      operationId: list-subscriptions
      parameters:
      - description: UUID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - default: 50
        description: Количество элементов (макс. 500)
        in: query
        name: limit
        type: integer
      - default: 0
        description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список подписок
          schema:
            $ref: '#/definitions/internal_service.listResp'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Список подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку на сервис
      operationId: create-subscription
      parameters:
      - description: Данные подписки
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_service.createReq'
      produces:
      - application/json
      responses:
        "201":
          description: Созданная подписка
          schema:
            $ref: '#/definitions/github_com_untibullet_subscription-service-em_internal_models.Subscription'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Создать новую подписку
      tags:
      - subscriptions
  /api/v1/subscriptions/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку по её ID
      operationId: delete-subscription
      parameters:
      - description: UUID идентификатор подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Подписка удалена
        "400":
          description: Неверный формат ID
          schema:
            $ref: '#/definitions/echo.Map'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает информацию о подписке по её уникальному идентификатору
      operationId: get-subscription-by-id
      parameters:
      - description: UUID идентификатор подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Информация о подписке
          schema:
            $ref: '#/definitions/github_com_untibullet_subscription-service-em_internal_models.Subscription'
        "400":
          description: Неверный формат ID
          schema:
            $ref: '#/definitions/echo.Map'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Получить подписку по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет существующую подписку по её ID
      operationId: update-subscription
      parameters:
      - description: UUID идентификатор подписки
        in: path
        name: id
        required: true
        type: string
      - description: Данные для обновления
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_service.updateReq'
      produces:
      - application/json
      responses:
        "200":
          description: Обновлённая подписка
          schema:
            $ref: '#/definitions/github_com_untibullet_subscription-service-em_internal_models.Subscription'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/echo.Map'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Обновить подписку
      tags:
      - subscriptions
  /api/v1/subscriptions/cost:
    get:
      consumes:
      - application/json
      description: Возвращает суммарную стоимость подписок пользователя или сервиса
        за указанный период
      operationId: calculate-cost
      parameters:
      - description: Начало периода (формат MM-YYYY)
        in: query
        name: start_period
        required: true
        type: string
      - description: Конец периода (формат MM-YYYY)
        in: query
        name: end_period
        required: true
        type: string
      - description: UUID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Суммарная стоимость
          schema:
            $ref: '#/definitions/internal_service.costResp'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/echo.Map'
      summary: Рассчитать стоимость подписок за период
      tags:
      - subscriptions
swagger: "2.0"
